[package]
name = "resource-foraging-evolution-simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
pixels = "0.15.0"
rand = "0.9.2"
winit = { version = "0.30.12", features = ["rwh_05"] }
